---
#-------------------------------
# General Site Settings

title: Connor Jones
logo:
author: themefisher
description: This is a webpage to display the portfolio/resume of Connor Jones
email: c.jones54166@gmail.com
phone: (830) 333-5864
#address: 125/A, CA Commercial Area, California, USA
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Connor


#-------------------------------
# About (Section and Page)

# About Section
blurb: A student at Gonzaga University studying computer science with increasing knowledge of various coding languages, who has become a dependable and responsible problem solver, with great time management skills. A quick and passionate learner that loves to learn new things while building on and engaging the knowledge of skills currently in possession. With experience in working with databases and software to help stores keep accurate data at all times.

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


#-------------------------------
# Skills Section

skills-title: Skills
skills:
   - { name: Software Development, color: "#9473e6", value: "80%" }
   - { name: data management, color: "#bdecf6", value: "70%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Data Management,
      icon: "icon-1.png",
      date: "May 2023 - Aug 2023",
      organization: "Mi Vida/Julien's",
    }
    
  - {
      name: Teaching Assistant,
      icon: "icon-2.png",
      date: "Sep 2023 - Present",
      organization: "Gonzaga School of Engineering & Applied Science",
    }
  

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Bachelor of Science in Computer Science,
      date: "2025",
      organization: "Gonzaga University",
    }

#-------------------------------
# Services Section

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-2.png"
    url: "https://github.com/Aldriik0/Connect4Project"
  - image: "assets/images/portfolio/item-9.png"
    url: "https://github.com/Aldriik0/Triumph-Tree"

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "Game Design", type: "game design"}

portfolio-items:
  - image: "assets/images/portfolio/item-2.png"
    url: "https://github.com/Aldriik0/Connect4Project"
    portfolio-type:
      - type: "design"
      - type: "game design"
  - image: "assets/images/portfolio/item-9.png"
    url: "https://github.com/Aldriik0/Triumph-Tree"
    portfolio-type:
        - type: "design"
        - type: "Mobile App"

  
#-------------------------------
# Testimonials Section

#-------------------------------
# Client Slider Section

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: c.jones54166@gmail.com
